### ISSUE TITLE
Como propietario de una tienda, quiero poder agregar productos a mi inventario para tener una lista completa de todo lo que tengo disponible para vender.

### ISSUE THREAD

**Issue by gespana26** [4GeeksAcademy/ProjectoFinal_Inventario#12]
- [x] Criterios de aceptación:
1.Puedo ingresar el nombre del producto, la descripción, el precio, la cantidad en stock y la categoría.
2.Puedo seleccionar un proveedor para el producto.

**Comment by gespana26** [comment]
- [x]  Se crea las relaciones entre las tablas de "products" y "detailsproduct."
- [x] se crea las funciones que permitan agregar, actualizar registros a las tablas "products" y "detailsproduct."

**Comment by gespana26** [comment]
- [x] Se crea las funciones que permitan borrar y buscar un producto por ID

**Comment by gespana26** [comment]
- [x] Kevin especifica las actividades en la tarea [#13](https://github.com/4GeeksAcademy/ProjectoFinal_Inventario/issues/13)
